### ISSUE TITLE
As a developer, I need to port the Cron report to Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#19]
This report should be pretty straight forward.
# Checks
## Enabled
- [x] Determine when cron last ran
- [x] Determine how often cron runs
- [x] Do not include elysia_cron (no D8 version) or ultimate_cron (no maintained D8 version)
- [x] If no threshold but it's been run within the last day, pass
- [x] If no threshold and it hasn't been run in a day, fail
- [x] Warn if there is a threshold but it hasn't run in the last day or the threshold is longer than a day
- [x] Pass if there is a threshold and it's run in the last day
- [x] If it fails for any reason, abort
## Last
- [x] Report the last time it ran
## Running
- [ ] Check to see if it's actively running (cron_semaphore may still be valid way of checking, verify)
- [ ] Warn if it's been running for more than an hour
- [ ] Info otherwise

**Comment by fluxsauce** [comment]
Are you on track to complete this by the 24th? I haven't seen any progress.

**Comment by shivanshuag** [comment]
I was stuck on the content checks. I have started working on this now. 
In the Running check, cron_semaphore is no longer the valid way of checking even in Drupal 7. I was removed somtime ago. Since the lock acquired by cron has a timeout limit, I don't think this check is needed in both - Drupal 7 and Drupal 8

**Comment by shivanshuag** [comment]
fixed in #30
